export type ProjectId = "interest" | "club" | "magazine";
export type CodeFile = "html" | "css" | "javascript";
export type ActivityType = "challenge" | "project" | "quiz";

export type PracticeQuestion = {
  prompt: string;
  options: [string, string, string];
  answer: number;
  explanation: string;
};

export type CodeTest = {
  file: CodeFile;
  label: string;
  pattern: string;
};

export type WorkspaceFiles = { html: string; css: string; javascript: string };

export type Lesson = {
  id: string;
  title: string;
  minutes: number;
  objective: string;
  activityType: ActivityType;
  activityNumber: number;
  language: "HTML" | "CSS" | "JavaScript" | "Web project";
  explanation: string[];
  keyTerms: string[];
  exampleTitle: string;
  exampleCode: string;
  exampleExplanation: string;
  task: string;
  starterFiles: WorkspaceFiles;
  editableFiles: CodeFile[];
  tests: CodeTest[];
  hints: [string, string, string];
  question?: PracticeQuestion;
  questions?: PracticeQuestion[];
  reflection?: string;
};

export type Stage = {
  id: string;
  number: number;
  title: string;
  description: string;
  outcome: string;
  lessons: Lesson[];
};

export const projectChoices: Array<{
  id: ProjectId;
  title: string;
  pitch: string;
  siteTitle: string;
  intro: string;
  items: [string, string, string];
}> = [
  { id: "interest", title: "Interest Guide", pitch: "Teach visitors about a topic you enjoy.", siteTitle: "The Interest Guide", intro: "A clear guide to a topic worth exploring.", items: ["What it is", "Why it matters", "Where to begin"] },
  { id: "club", title: "Club Website", pitch: "Create a home page for a fictional club or team.", siteTitle: "The Saturday Club", intro: "A place for people who enjoy learning together.", items: ["About the club", "Weekly activities", "How to take part"] },
  { id: "magazine", title: "Mini Magazine", pitch: "Publish short articles about a subject you choose.", siteTitle: "The Small Magazine", intro: "Short articles, useful ideas and thoughtful recommendations.", items: ["Latest article", "Editor picks", "Reader notes"] },
];

const files = (html: string, css = "", javascript = ""): WorkspaceFiles => ({ html, css, javascript });
const q = (prompt: string, correct: string, wrongOne: string, wrongTwo: string, explanation: string): PracticeQuestion => ({ prompt, options: [correct, wrongOne, wrongTwo], answer: 0, explanation });
const t = (file: CodeFile, label: string, pattern: string): CodeTest => ({ file, label, pattern });

type LessonSeed = Omit<Lesson, "id" | "activityType" | "activityNumber"> & { id: string };

function makeStage(input: {
  id: string;
  number: number;
  title: string;
  description: string;
  outcome: string;
  challenges: LessonSeed[];
  project: LessonSeed;
  projectQuestion: PracticeQuestion;
}): Stage {
  const challenges = input.challenges.map((lesson, index): Lesson => ({ ...lesson, id: `${input.id}-${lesson.id}`, activityType: "challenge", activityNumber: index + 1 }));
  const project: Lesson = { ...input.project, id: `${input.id}-project`, activityType: "project", activityNumber: 5 };
  const questions = [...challenges.map((lesson) => lesson.question!), input.projectQuestion];
  const quiz: Lesson = {
    id: `${input.id}-quiz`, title: `${input.title} check`, minutes: 8, objective: "Check the ideas you used before opening the next module.", activityType: "quiz", activityNumber: 6,
    language: challenges[0].language, explanation: ["Answer five questions. Four correct answers unlock the next module."], keyTerms: Array.from(new Set(challenges.flatMap((lesson) => lesson.keyTerms))),
    exampleTitle: "Review first", exampleCode: "Read the question, predict an answer, then choose.", exampleExplanation: "Every answer was taught and used in this module.", task: "Answer all five questions.",
    starterFiles: files(""), editableFiles: [], tests: [], hints: ["Return to the lesson that introduced the term.", "Read each code example again.", "Try a fresh attempt after reviewing."], questions,
  };
  return { id: input.id, number: input.number, title: input.title, description: input.description, outcome: input.outcome, lessons: [...challenges, project, quiz] };
}

const shared = {
  htmlProject: "<header><h1>{{TITLE}}</h1></header>\n<main>\n  <p>{{INTRO}}</p>\n  <section class=\"cards\">\n    <article class=\"card\"><h2>{{ITEM1}}</h2><p>Add useful information here.</p></article>\n    <article class=\"card\"><h2>{{ITEM2}}</h2><p>Add useful information here.</p></article>\n    <article class=\"card\"><h2>{{ITEM3}}</h2><p>Add useful information here.</p></article>\n  </section>\n</main>\n<footer><p>Built while learning web development.</p></footer>",
  cssProject: "body { margin: 0; padding: 2rem; background: #f7f3ea; color: #111936; font-family: Arial, sans-serif; }\nh1 { color: #4b1f63; }\n.cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }\n.card { padding: 1rem; border: 2px solid #111936; border-radius: 12px; }\n@media (max-width: 650px) { .cards { grid-template-columns: 1fr; } }",
};

export const stages: Stage[] = [
  makeStage({
    id: "html-foundations", number: 1, title: "Write your first HTML", description: "Use tags to turn plain text into a structured webpage.", outcome: "A page with a title, introduction and organised list.",
    challenges: [
      { id: "elements", title: "Create an HTML element", minutes: 8, objective: "Write an opening tag, content and a closing tag.", language: "HTML", explanation: ["HTML gives a webpage structure. Most elements have an opening tag, content and a closing tag.", "The tag name tells the browser what the content means. h1 means the main heading."], keyTerms: ["element", "opening tag", "closing tag"], exampleTitle: "A paragraph element", exampleCode: "<p>I am learning to build websites.</p>", exampleExplanation: "The first p tag starts the paragraph and the second one closes it.", task: "Replace the plain text with an h1 element that says My First Website.", starterFiles: files("My First Website"), editableFiles: ["html"], tests: [t("html", "Your page has the required h1", "<h1[^>]*>\\s*My First Website\\s*</h1>")], hints: ["A main heading begins with <h1>.", "Put the words between the two tags.", "Use <h1>My First Website</h1>."], question: q("What marks the main heading?", "The h1 element", "The file name", "The space bar", "h1 represents the main heading." ) },
      { id: "text", title: "Add headings and paragraphs", minutes: 10, objective: "Use headings for titles and paragraphs for normal text.", language: "HTML", explanation: ["Headings organise the page. h1 names the page and h2 introduces an important section.", "Paragraphs hold normal sentences. Choosing the right element gives content meaning."], keyTerms: ["heading", "paragraph", "structure"], exampleTitle: "Two levels of content", exampleCode: "<h1>Photography</h1>\n<h2>First tip</h2>\n<p>Use light to make the subject clear.</p>", exampleExplanation: "Each element has a different job.", task: "Add an h2 saying About this page and a paragraph below it.", starterFiles: files("<h1>My First Website</h1>\n\n<!-- Add your section -->"), editableFiles: ["html"], tests: [t("html", "The page has an About this page heading", "<h2[^>]*>\\s*About this page\\s*</h2>"), t("html", "The section has a paragraph", "<p[^>]*>[^<]+</p>")], hints: ["Add the h2 before the paragraph.", "A paragraph uses p tags.", "Write <h2>About this page</h2>, then add your paragraph."], question: q("Which element is best for a normal sentence?", "p", "h1", "img", "The p element represents a paragraph.") },
      { id: "nesting", title: "Nest related elements", minutes: 10, objective: "Put related elements inside a section correctly.", language: "HTML", explanation: ["Nesting means placing an element inside another. It groups content that belongs together.", "Close the inner element before the outer element. Indentation makes the relationship easier to see."], keyTerms: ["nesting", "parent", "child"], exampleTitle: "A section containing text", exampleCode: "<section>\n  <h2>About</h2>\n  <p>This content belongs together.</p>\n</section>", exampleExplanation: "The heading and paragraph are children of the section.", task: "Place the h2 and paragraph inside a section element.", starterFiles: files("<h2>About this page</h2>\n<p>This page shares useful ideas.</p>"), editableFiles: ["html"], tests: [t("html", "A section contains the heading and paragraph", "<section[^>]*>[\\s\\S]*<h2[^>]*>[\\s\\S]*</h2>[\\s\\S]*<p[^>]*>[\\s\\S]*</p>[\\s\\S]*</section>")], hints: ["Add <section> before the h2.", "Close the section after the paragraph.", "Indent the h2 and p inside the section."], question: q("What does nesting show?", "Which elements belong inside another", "How fast a page loads", "The browser colour", "Nesting shows parent and child relationships.") },
      { id: "lists", title: "Build a useful list", minutes: 10, objective: "Create an unordered list with three list items.", language: "HTML", explanation: ["A list groups related items. Use ul when the order does not matter and ol when it does.", "Every item belongs inside an li element."], keyTerms: ["unordered list", "ordered list", "list item"], exampleTitle: "Three materials", exampleCode: "<ul>\n  <li>Notebook</li>\n  <li>Pencil</li>\n  <li>Ruler</li>\n</ul>", exampleExplanation: "The ul groups three li elements.", task: "Complete the list by adding two more li elements.", starterFiles: files("<h2>What you will find</h2>\n<ul>\n  <li>Clear explanations</li>\n</ul>"), editableFiles: ["html"], tests: [t("html", "The list contains at least three items", "<ul[^>]*>[\\s\\S]*<li[^>]*>[\\s\\S]*</li>[\\s\\S]*<li[^>]*>[\\s\\S]*</li>[\\s\\S]*<li[^>]*>[\\s\\S]*</li>[\\s\\S]*</ul>")], hints: ["Add new li elements before </ul>.", "Every item needs opening and closing li tags.", "Follow the example using your own words."], question: q("Where do li elements belong?", "Inside a ul or ol", "Inside an img", "Outside the page", "List items belong inside a list.") },
    ],
    project: { id: "project", title: "Build the page introduction", minutes: 18, objective: "Create the first working version of your website.", language: "Web project", explanation: ["This is your project file. Later modules will improve the same website."], keyTerms: ["page structure", "content"], exampleTitle: "Required structure", exampleCode: "<main>\n  <h1>Page title</h1>\n  <p>Introduction</p>\n  <h2>Inside this site</h2>\n  <ul>...</ul>\n</main>", exampleExplanation: "The main element contains the important page content.", task: "Create a title, introduction and three-item list for your chosen website.", starterFiles: files("<main>\n  <h1>{{TITLE}}</h1>\n  <p>{{INTRO}}</p>\n  <!-- Add an h2 and a three-item list -->\n</main>"), editableFiles: ["html"], tests: [t("html", "The project has one main heading", "<h1[^>]*>[^<]+</h1>"), t("html", "The project has an introduction", "<p[^>]*>[^<]+</p>"), t("html", "The project has a section heading", "<h2[^>]*>[^<]+</h2>"), t("html", "The project has a three-item list", "<ul[^>]*>[\\s\\S]*<li[^>]*>[\\s\\S]*</li>[\\s\\S]*<li[^>]*>[\\s\\S]*</li>[\\s\\S]*<li[^>]*>[\\s\\S]*</li>[\\s\\S]*</ul>")], hints: ["Build one requirement at a time.", "Keep visible text inside HTML elements.", "Compare the structure with the example."], question: q("What does this first version prove?", "The learner can structure real content", "The page has animation", "The page uses a database", "The checkpoint proves basic HTML structure."), reflection: "Which element organised your page most clearly?" },
    projectQuestion: q("Which element should contain the main page content?", "main", "title", "script", "main holds the primary content."),
  }),
  makeStage({
    id: "html-content", number: 2, title: "Connect and describe content", description: "Add links, images and meaningful page regions.", outcome: "A complete HTML page that works before styling.",
    challenges: [
      { id: "links", title: "Create a working link", minutes: 9, objective: "Use an anchor and href attribute.", language: "HTML", explanation: ["The a element creates a link. Its href attribute stores the destination.", "Good link text explains where the link goes."], keyTerms: ["anchor", "attribute", "href"], exampleTitle: "A descriptive link", exampleCode: "<a href=\"https://example.com\">Read the guide</a>", exampleExplanation: "href contains the address and the visible words describe it.", task: "Turn Read more into a link to https://example.com.", starterFiles: files("<p>Find another useful explanation.</p>\n<p>Read more</p>"), editableFiles: ["html"], tests: [t("html", "Read more links to the correct address", "<a[^>]+href=[\"']https://example\\.com/?[\"'][^>]*>\\s*Read more\\s*</a>")], hints: ["Replace the second p with an a element.", "Add href inside the opening tag.", "Use <a href=\"https://example.com\">Read more</a>."], question: q("Which attribute holds a link destination?", "href", "alt", "class", "href tells the link where to go.") },
      { id: "images", title: "Describe an image", minutes: 10, objective: "Use src and alt attributes correctly.", language: "HTML", explanation: ["img displays an image from its src address.", "Alternative text communicates the image's meaning when it cannot be seen or loaded."], keyTerms: ["image", "src", "alternative text"], exampleTitle: "Useful alternative text", exampleCode: "<img src=\"camera.jpg\" alt=\"A camera beside a notebook\">", exampleExplanation: "The description communicates the important information.", task: "Add a useful alt description to the image.", starterFiles: files("<img src=\"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800\">"), editableFiles: ["html"], tests: [t("html", "The image has a useful alt description", "<img[^>]+alt=[\"'][^\"']{5,}[\"'][^>]*>")], hints: ["Add alt inside the img element.", "Describe what matters in the picture.", "For example: alt=\"A laptop open on a desk\"."], question: q("Why does an image need alt text?", "To communicate its meaning when it cannot be seen", "To download it twice", "To make it a heading", "Alternative text makes image information available.") },
      { id: "semantics", title: "Use meaningful page regions", minutes: 11, objective: "Structure a page with header, main and footer.", language: "HTML", explanation: ["Semantic elements name the job of each page region.", "A header introduces the page, main contains central content and footer ends the page."], keyTerms: ["semantic HTML", "header", "main", "footer"], exampleTitle: "A meaningful outline", exampleCode: "<header><h1>Guide</h1></header>\n<main><p>Main information.</p></main>\n<footer><p>Practice project.</p></footer>", exampleExplanation: "The tag names explain the purpose of each region.", task: "Replace the three div elements with header, main and footer.", starterFiles: files("<div><h1>My Guide</h1></div>\n<div><p>The main information.</p></div>\n<div><p>Made for practice.</p></div>"), editableFiles: ["html"], tests: [t("html", "The page has a header", "<header[\\s>]"), t("html", "The page has a main region", "<main[\\s>]"), t("html", "The page has a footer", "<footer[\\s>]")], hints: ["Change only the tag names first.", "Match every opening and closing tag.", "Use header, then main, then footer."], question: q("Which element contains the central information?", "main", "footer", "style", "main contains the primary content.") },
      { id: "forms", title: "Label an input", minutes: 12, objective: "Connect a label and input using for and id.", language: "HTML", explanation: ["Forms collect information. Inputs need labels that explain what to enter.", "The label for value must match the input id."], keyTerms: ["form", "label", "input", "id"], exampleTitle: "A connected label", exampleCode: "<label for=\"topic\">Favourite topic</label>\n<input id=\"topic\" type=\"text\">", exampleExplanation: "Both elements use topic, so the browser connects them.", task: "Connect the email label and set the input type to email.", starterFiles: files("<label>Email address</label>\n<input>"), editableFiles: ["html"], tests: [t("html", "The label points to email", "<label[^>]+for=[\"']email[\"'][^>]*>"), t("html", "The input has matching id and email type", "<input[^>]+(?:id=[\"']email[\"'][^>]+type=[\"']email[\"']|type=[\"']email[\"'][^>]+id=[\"']email[\"'])[^>]*>")], hints: ["Add for=\"email\" to the label.", "Add id=\"email\" to the input.", "The input also needs type=\"email\"."], question: q("How do you connect a label and input?", "Match label for with input id", "Give them the same colour", "Put both in a paragraph", "Matching values create the connection.") },
    ],
    project: { id: "project", title: "Complete the HTML structure", minutes: 20, objective: "Turn the first project into a complete semantic page.", language: "Web project", explanation: ["Keep the structure you already built. Add a useful link, described image and labelled input."], keyTerms: ["semantic structure", "accessible content"], exampleTitle: "A complete outline", exampleCode: "<header>...</header>\n<main><section>...</section></main>\n<footer>...</footer>", exampleExplanation: "A clear outline makes later styling easier.", task: "Add semantic regions, one link, one described image and a labelled email input.", starterFiles: files(shared.htmlProject), editableFiles: ["html"], tests: [t("html", "The project uses header, main and footer", "<header[\\s>][\\s\\S]*<main[\\s>][\\s\\S]*<footer[\\s>]"), t("html", "The project has a working link", "<a[^>]+href=[\"'][^\"']+[\"'][^>]*>"), t("html", "The image has alternative text", "<img[^>]+alt=[\"'][^\"']{5,}[\"'][^>]*>"), t("html", "A label and input are connected", "<label[^>]+for=[\"']([^\"']+)[\"'][^>]*>[\\s\\S]*<input[^>]+id=[\"'][^\"']+[\"']")], hints: ["Start with header, main and footer.", "Add one feature and run before the next.", "Check that label and input share the same word."], question: q("Why finish HTML before design?", "Clear structure gives CSS meaningful content to style", "CSS deletes HTML", "Design works without text", "Strong HTML supports styling and accessibility."), reflection: "Which change made the page easier to understand?" },
    projectQuestion: q("Which feature explains an unseen image?", "Alternative text", "A larger margin", "A loop", "Alternative text communicates the image's meaning."),
  }),
  makeStage({
    id: "css-foundations", number: 3, title: "Style with CSS", description: "Use selectors and declarations to control presentation.", outcome: "A consistent colour, type and component style.",
    challenges: [
      { id: "rules", title: "Write a CSS rule", minutes: 9, objective: "Use a selector, property and value.", language: "CSS", explanation: ["A CSS rule begins with a selector that chooses HTML.", "Declarations sit inside braces and contain a property and value."], keyTerms: ["selector", "property", "value"], exampleTitle: "Style every paragraph", exampleCode: "p {\n  color: #2d1948;\n}", exampleExplanation: "p selects paragraphs and color changes their text.", task: "Change every h1 to #4b1f63.", starterFiles: files("<h1>Style this heading</h1>", "/* Write CSS here */"), editableFiles: ["css"], tests: [t("css", "The h1 colour is #4b1f63", "h1\\s*\\{[\\s\\S]*color\\s*:\\s*#4b1f63")], hints: ["Start with h1.", "Put the declaration inside braces.", "Use color: #4b1f63;."], question: q("What chooses the HTML element in CSS?", "The selector", "The value", "The semicolon", "The selector chooses the elements to style.") },
      { id: "classes", title: "Reuse a class", minutes: 10, objective: "Style selected elements with a class.", language: "CSS", explanation: ["A class lets several elements share one style.", "HTML uses class and CSS selects it with a full stop."], keyTerms: ["class", "class selector", "reuse"], exampleTitle: "A highlighted note", exampleCode: "<p class=\"note\">Remember this.</p>\n\n.note { font-weight: bold; }", exampleExplanation: "The class name connects the HTML and CSS.", task: "Create a .featured class for the second article.", starterFiles: files("<article>First</article>\n<article class=\"featured\">Second</article>", "/* Style only .featured */"), editableFiles: ["css", "html"], tests: [t("html", "An element uses the featured class", "class=[\"'][^\"']*featured"), t("css", "CSS selects the featured class", "\\.featured\\s*\\{")], hints: ["The HTML already has the class.", "Select it with .featured.", "Add a declaration inside the rule."], question: q("How does CSS select class card?", ".card", "#card", "<card>", "A full stop begins a class selector.") },
      { id: "type", title: "Make text readable", minutes: 11, objective: "Set font size, line height and width.", language: "CSS", explanation: ["Readable text needs enough size and space between lines.", "max-width prevents tiring lines that stretch too far."], keyTerms: ["font size", "line height", "max width"], exampleTitle: "Readable paragraph settings", exampleCode: "p { font-size: 1rem; line-height: 1.6; max-width: 65ch; }", exampleExplanation: "The ch unit measures approximate character width.", task: "Set paragraphs to 1rem, line-height 1.6 and max-width 60ch.", starterFiles: files("<p>Good typography makes content easier to understand.</p>", "p {\n  /* Add three declarations */\n}"), editableFiles: ["css"], tests: [t("css", "Font size is 1rem", "font-size\\s*:\\s*1rem"), t("css", "Line height is 1.6", "line-height\\s*:\\s*1\\.6"), t("css", "Maximum width is 60ch", "max-width\\s*:\\s*60ch")], hints: ["Write one declaration per line.", "Use the exact property names.", "Place a colon between each property and value."], question: q("What controls space between text lines?", "line-height", "border", "display", "line-height controls vertical spacing in text.") },
      { id: "cards", title: "Style a content card", minutes: 12, objective: "Combine background, border and corners.", language: "CSS", explanation: ["A card groups related information without changing its meaning.", "Background, border and border-radius define that group."], keyTerms: ["background", "border", "border radius"], exampleTitle: "A simple card", exampleCode: ".card { background: #fffdf8; border: 2px solid #18213f; border-radius: 12px; }", exampleExplanation: "Three properties create a clear card surface.", task: "Give .card the three styles shown in the example.", starterFiles: files("<article class=\"card\">Useful information</article>", ".card {\n  /* Add the styles */\n}"), editableFiles: ["css"], tests: [t("css", "The card has an off-white background", "background(?:-color)?\\s*:\\s*#fffdf8"), t("css", "The card has a 2px solid border", "border\\s*:\\s*2px\\s+solid\\s+#18213f"), t("css", "Corners use a 12px radius", "border-radius\\s*:\\s*12px")], hints: ["Put all declarations inside .card.", "Copy the values exactly.", "Check every colon and semicolon."], question: q("What rounds an element's corners?", "border-radius", "font-size", "href", "border-radius controls corner shape.") },
    ],
    project: { id: "project", title: "Create the visual system", minutes: 22, objective: "Apply a consistent design to the project.", language: "Web project", explanation: ["Keep the HTML. Add reusable CSS for the page, text, links and cards."], keyTerms: ["stylesheet", "visual system", "class"], exampleTitle: "A small design system", exampleCode: "body { ... }\nh1 { ... }\n.card { ... }\na { ... }", exampleExplanation: "A few deliberate rules can style the whole page.", task: "Style the body, main heading, links and at least one card class.", starterFiles: files(shared.htmlProject, "/* Build your visual system */"), editableFiles: ["html", "css"], tests: [t("css", "The page has a background", "body\\s*\\{[\\s\\S]*background"), t("css", "The main heading has its own rule", "h1\\s*\\{"), t("css", "Links have their own rule", "a(?:[\\s:{.#]|$)[\\s\\S]*\\{"), t("css", "A card class is styled", "\\.card\\s*\\{")], hints: ["Begin with body and h1 rules.", "Use the existing .card class.", "Run after every two declarations."], question: q("Why use a class for repeated cards?", "One rule styles several elements", "It changes HTML into JavaScript", "It removes the text", "Classes make styles reusable."), reflection: "Which CSS choice improved readability most?" },
    projectQuestion: q("What connects class=card to CSS?", "The .card selector", "The href attribute", "A loop", ".card matches the HTML class."),
  }),
  makeStage({
    id: "css-layout", number: 4, title: "Build flexible layouts", description: "Control spacing and arrange content for different screens.", outcome: "A responsive page for phones and larger screens.",
    challenges: [
      { id: "box", title: "Use the box model", minutes: 11, objective: "Use padding and margin for different space.", language: "CSS", explanation: ["Content sits inside a box. Padding adds inner space and margin adds outer space.", "Choose the property based on where the space belongs."], keyTerms: ["box model", "padding", "margin"], exampleTitle: "Inner and outer space", exampleCode: ".card { padding: 1rem; margin-bottom: 1.5rem; }", exampleExplanation: "Padding opens the inside and margin separates the next card.", task: "Add 1rem padding and 2rem bottom margin.", starterFiles: files("<article class=\"card\">A card needs space.</article>", ".card { border: 2px solid #18213f; }"), editableFiles: ["css"], tests: [t("css", "The card has 1rem inner space", "padding\\s*:\\s*1rem"), t("css", "The card has 2rem space below", "margin-bottom\\s*:\\s*2rem")], hints: ["Both declarations go inside .card.", "Padding is inner space.", "margin-bottom is outside and below."], question: q("What adds space inside a border?", "padding", "margin", "display", "Padding creates inner space.") },
      { id: "flex", title: "Arrange a row with Flexbox", minutes: 12, objective: "Place navigation links in a row.", language: "CSS", explanation: ["Flexbox arranges items along one main direction.", "Set display: flex on the parent and gap for consistent spacing."], keyTerms: ["Flexbox", "flex container", "gap"], exampleTitle: "A navigation row", exampleCode: "nav { display: flex; gap: 1rem; }", exampleExplanation: "The nav becomes the flex container.", task: "Make nav a flex container with a 1rem gap.", starterFiles: files("<nav><a href=\"#one\">One</a><a href=\"#two\">Two</a></nav>", "nav {\n  /* Add two declarations */\n}"), editableFiles: ["css"], tests: [t("css", "Navigation uses Flexbox", "nav\\s*\\{[\\s\\S]*display\\s*:\\s*flex"), t("css", "Navigation has a 1rem gap", "nav\\s*\\{[\\s\\S]*gap\\s*:\\s*1rem")], hints: ["The parent is nav.", "Use display: flex first.", "Add gap in the same rule."], question: q("Where does display:flex belong?", "On the parent of the items", "Inside href", "In the address bar", "The parent becomes the flex container.") },
      { id: "grid", title: "Create a card grid", minutes: 13, objective: "Use CSS Grid for equal columns.", language: "CSS", explanation: ["Grid controls rows and columns together.", "repeat makes equal tracks without repeating the size."], keyTerms: ["CSS Grid", "column", "repeat"], exampleTitle: "Three equal columns", exampleCode: ".grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }", exampleExplanation: "1fr is one equal fraction of available space.", task: "Make .grid two equal columns with a 1rem gap.", starterFiles: files("<section class=\"grid\"><article>A</article><article>B</article></section>", ".grid {\n  /* Build the grid */\n}"), editableFiles: ["css"], tests: [t("css", "The section uses Grid", "\\.grid\\s*\\{[\\s\\S]*display\\s*:\\s*grid"), t("css", "The grid has two equal columns", "grid-template-columns\\s*:\\s*repeat\\(2\\s*,\\s*1fr\\)"), t("css", "The grid has a 1rem gap", "gap\\s*:\\s*1rem")], hints: ["Start with display:grid.", "Use repeat(2, 1fr).", "Add gap after the columns."], question: q("What does 1fr mean?", "One equal fraction of available space", "One pixel", "One form", "fr shares available grid space.") },
      { id: "responsive", title: "Adapt to small screens", minutes: 14, objective: "Use a media query for a narrow screen.", language: "CSS", explanation: ["Responsive design lets one page work on different screens.", "A media query applies rules when its condition is true."], keyTerms: ["responsive design", "media query", "breakpoint"], exampleTitle: "One narrow column", exampleCode: "@media (max-width: 600px) { .grid { grid-template-columns: 1fr; } }", exampleExplanation: "The grid becomes one column at 600px or below.", task: "At 650px or below, change .grid to one column.", starterFiles: files("<section class=\"grid\"><article>One</article><article>Two</article></section>", ".grid { display: grid; grid-template-columns: repeat(2, 1fr); }\n\n/* Add the media query */"), editableFiles: ["css"], tests: [t("css", "A 650px media query creates one column", "@media\\s*\\(max-width\\s*:\\s*650px\\)[\\s\\S]*\\.grid\\s*\\{[\\s\\S]*grid-template-columns\\s*:\\s*1fr")], hints: ["Begin with @media (max-width: 650px).", "Add a .grid rule inside it.", "Set grid-template-columns: 1fr."], question: q("What does a media query do?", "Applies styles when a screen condition is true", "Stores a password", "Creates a heading", "Media queries adapt the layout to conditions.") },
    ],
    project: { id: "project", title: "Make the project responsive", minutes: 24, objective: "Use spacing, Flexbox, Grid and a media query.", language: "Web project", explanation: ["The goal is a clear layout at wide and narrow sizes, not extra decoration."], keyTerms: ["layout", "Flexbox", "Grid", "responsive"], exampleTitle: "A layout plan", exampleCode: "nav { display:flex; }\n.cards { display:grid; }\n@media (max-width:650px) { ... }", exampleExplanation: "Each layout tool has one job.", task: "Create flexible navigation, a card grid and a one-column mobile layout.", starterFiles: files("<header><h1>{{TITLE}}</h1><nav><a href=\"#learn\">Learn</a><a href=\"#about\">About</a></nav></header>\n<main><p>{{INTRO}}</p><section class=\"cards\"><article class=\"card\">{{ITEM1}}</article><article class=\"card\">{{ITEM2}}</article><article class=\"card\">{{ITEM3}}</article></section></main>", "body { padding: 2rem; background: #f7f3ea; color: #111936; font-family: Arial, sans-serif; } .card { padding: 1rem; border: 2px solid #111936; }\n/* Add layout rules */"), editableFiles: ["html", "css"], tests: [t("css", "Navigation uses Flexbox", "nav\\s*\\{[\\s\\S]*display\\s*:\\s*flex"), t("css", "Cards use Grid", "\\.cards\\s*\\{[\\s\\S]*display\\s*:\\s*grid"), t("css", "The layout uses gap", "gap\\s*:"), t("css", "A media query creates one column", "@media[\\s\\S]*\\.cards\\s*\\{[\\s\\S]*grid-template-columns\\s*:\\s*1fr")], hints: ["Give nav and .cards separate rules.", "Use repeat for the wide grid.", "Put the one-column rule in a media query."], question: q("What should happen on a narrow screen?", "The layout should adapt and stay readable", "The page should force sideways scrolling", "The content should disappear", "Responsive layouts protect usability."), reflection: "What changed when you made the preview narrow?" },
    projectQuestion: q("What is best for a row of navigation links?", "Flexbox", "Alternative text", "A JavaScript number", "Flexbox suits a one-dimensional row."),
  }),
  makeStage({
    id: "javascript-foundations", number: 5, title: "Start programming with JavaScript", description: "Store information, calculate values and organise instructions.", outcome: "JavaScript that updates useful page information.",
    challenges: [
      { id: "output", title: "Run your first JavaScript", minutes: 9, objective: "Change visible text with code.", language: "JavaScript", explanation: ["JavaScript adds behaviour to a webpage.", "querySelector finds an element and textContent changes its words."], keyTerms: ["JavaScript", "statement", "textContent"], exampleTitle: "Change a message", exampleCode: "document.querySelector(\"#message\").textContent = \"JavaScript is running\";", exampleExplanation: "The statement finds #message and replaces its text.", task: "Change #status to JavaScript is running.", starterFiles: files("<p id=\"status\">Waiting for code...</p>", "", "// Write JavaScript here"), editableFiles: ["javascript"], tests: [t("javascript", "JavaScript changes the status", "querySelector\\([\"']#status[\"']\\)[\\s\\S]*textContent\\s*=\\s*[\"']JavaScript is running[\"']")], hints: ["Select #status.", "Use textContent.", "Follow the example with the new id."], question: q("What does textContent change?", "The text inside an element", "The browser address", "The file name", "textContent reads or changes element text.") },
      { id: "variables", title: "Store a changing value", minutes: 10, objective: "Create and update a variable with let.", language: "JavaScript", explanation: ["A variable gives a value a useful name. let is used when the value may change.", "The equals sign assigns the right-hand value to the name on the left."], keyTerms: ["variable", "let", "assignment"], exampleTitle: "A changing count", exampleCode: "let articleCount = 2;\narticleCount = articleCount + 1;", exampleExplanation: "The value begins at 2 and becomes 3.", task: "Create topicCount as 3, then increase it by 1.", starterFiles: files("<p>Open JavaScript.</p>", "", "// Create and update topicCount"), editableFiles: ["javascript"], tests: [t("javascript", "topicCount begins at 3", "let\\s+topicCount\\s*=\\s*3"), t("javascript", "topicCount increases by 1", "topicCount\\s*=\\s*topicCount\\s*\\+\\s*1")], hints: ["Begin with let topicCount = 3;.", "Use the name again on line two.", "Assign topicCount + 1 back to topicCount."], question: q("When is let useful?", "When a stored value may change", "When adding image alt text", "When creating a border", "let declares a value that can be reassigned.") },
      { id: "types", title: "Use strings and numbers", minutes: 11, objective: "Distinguish text values from numbers.", language: "JavaScript", explanation: ["A string stores text inside quotes. A number is written without quotes.", "Correct types matter because numbers calculate while strings can join as text."], keyTerms: ["string", "number", "data type"], exampleTitle: "Two value types", exampleCode: "const topic = \"Robotics\";\nconst minutes = 15;", exampleExplanation: "topic is text and minutes is a number.", task: "Create a string sectionName and a number itemCount.", starterFiles: files("<p id=\"result\"></p>", "", "// Create the two values"), editableFiles: ["javascript"], tests: [t("javascript", "sectionName stores text", "(?:const|let)\\s+sectionName\\s*=\\s*[\"'][^\"']+[\"']"), t("javascript", "itemCount stores a number", "(?:const|let)\\s+itemCount\\s*=\\s*\\d+")], hints: ["Put sectionName text in quotes.", "Do not quote itemCount.", "Use const or let before each name."], question: q("Which is a number?", "12", "\"12\"", "\"twelve\"", "Numbers do not use quotation marks.") },
      { id: "functions", title: "Organise code with a function", minutes: 13, objective: "Define and call a function.", language: "JavaScript", explanation: ["A function groups instructions that perform one job.", "Defining prepares it. Calling the function runs it."], keyTerms: ["function", "define", "call"], exampleTitle: "Show a welcome message", exampleCode: "function showWelcome() {\n  document.querySelector(\"#message\").textContent = \"Welcome\";\n}\nshowWelcome();", exampleExplanation: "The final line calls the function.", task: "Complete showTopic, then call it.", starterFiles: files("<p id=\"topic\">No topic selected</p>", "", "function showTopic() {\n  // Change #topic text\n}\n\n// Call the function"), editableFiles: ["javascript"], tests: [t("javascript", "showTopic is defined", "function\\s+showTopic\\s*\\("), t("javascript", "The function changes #topic", "querySelector\\([\"']#topic[\"']\\)[\\s\\S]*textContent\\s*="), t("javascript", "showTopic is called", "showTopic\\s*\\(\\s*\\)\\s*;?\\s*$")], hints: ["Write textContent inside the braces.", "Close the function before calling it.", "Add showTopic(); on the final line."], question: q("What runs a defined function?", "Calling it", "Naming the HTML file", "Adding a CSS class", "A function runs when it is called.") },
    ],
    project: { id: "project", title: "Add useful page information", minutes: 24, objective: "Use variables and a function in the project.", language: "Web project", explanation: ["Add JavaScript without removing the HTML and CSS. Show one useful value on the page."], keyTerms: ["variable", "function", "output"], exampleTitle: "A project function", exampleCode: "const total = 3;\nfunction showTotal() { totalText.textContent = total; }\nshowTotal();", exampleExplanation: "A named value is shown through a function.", task: "Create pageTitle, itemCount and showSummary, then update #summary.", starterFiles: files("<header><h1>{{TITLE}}</h1></header><main><p>{{INTRO}}</p><p id=\"summary\">Summary loading...</p><section class=\"cards\"><article class=\"card\">{{ITEM1}}</article><article class=\"card\">{{ITEM2}}</article><article class=\"card\">{{ITEM3}}</article></section></main>", shared.cssProject, "// Add values and a function"), editableFiles: ["html", "css", "javascript"], tests: [t("javascript", "pageTitle stores text", "(?:const|let)\\s+pageTitle\\s*=\\s*[\"'][^\"']+[\"']"), t("javascript", "itemCount stores a number", "(?:const|let)\\s+itemCount\\s*=\\s*\\d+"), t("javascript", "showSummary is defined", "function\\s+showSummary\\s*\\("), t("javascript", "The function updates #summary and is called", "querySelector\\([\"']#summary[\"']\\)[\\s\\S]*textContent\\s*=[\\s\\S]*showSummary\\s*\\(")], hints: ["Create both variables before the function.", "Select #summary inside showSummary.", "Call showSummary after the function."], question: q("Why use a named function?", "The task becomes organised and reusable", "HTML stops working", "The browser hides the code", "Functions organise reusable instructions."), reflection: "What value did JavaScript place on the page?" },
    projectQuestion: q("Which line calls showSummary?", "showSummary();", "function showSummary", "#showSummary", "A name followed by parentheses calls the function."),
  }),
  makeStage({
    id: "javascript-logic", number: 6, title: "Make decisions and repeat work", description: "Use comparisons, conditions, arrays and loops.", outcome: "Code that chooses an outcome and handles several values.",
    challenges: [
      { id: "compare", title: "Compare values", minutes: 10, objective: "Create a boolean result.", language: "JavaScript", explanation: ["A comparison asks a question answered by true or false.", "Strict equality uses three equals signs and checks value and type."], keyTerms: ["comparison", "boolean", "strict equality"], exampleTitle: "Check a total", exampleCode: "const count = 3;\nconst complete = count === 3;", exampleExplanation: "complete becomes true.", task: "Create isReady by checking if lessonCount is exactly 4.", starterFiles: files("<p>Check the value.</p>", "", "const lessonCount = 4;\n// Create isReady"), editableFiles: ["javascript"], tests: [t("javascript", "isReady compares lessonCount with 4", "(?:const|let)\\s+isReady\\s*=\\s*lessonCount\\s*===\\s*4")], hints: ["Begin with const isReady =.", "Compare the existing variable.", "Use three equals signs."], question: q("What can a boolean hold?", "true or false", "Only sentences", "Only colours", "A boolean has two logical values.") },
      { id: "conditions", title: "Choose with if and else", minutes: 12, objective: "Run different code based on a condition.", language: "JavaScript", explanation: ["if runs its block when a condition is true.", "else handles the other outcome."], keyTerms: ["if", "else", "condition"], exampleTitle: "Choose a message", exampleCode: "if (count > 0) { message = \"Available\"; } else { message = \"Nothing yet\"; }", exampleExplanation: "Only one message is chosen.", task: "Set message to Ready when score is 5 or higher, otherwise Keep going.", starterFiles: files("<p id=\"message\"></p>", "", "const score = 5;\nlet message = \"\";\n// Add if and else\ndocument.querySelector(\"#message\").textContent = message;"), editableFiles: ["javascript"], tests: [t("javascript", "The condition checks score", "if\\s*\\(\\s*score\\s*>=\\s*5"), t("javascript", "The true result is Ready", "message\\s*=\\s*[\"']Ready[\"']"), t("javascript", "The else result is Keep going", "else\\s*\\{[\\s\\S]*message\\s*=\\s*[\"']Keep going[\"']")], hints: ["Place if before textContent.", "Use score >= 5.", "Add else after the first block."], question: q("When does an if block run?", "When its condition is true", "Whenever CSS loads", "Only when an image fails", "if runs when its condition evaluates to true.") },
      { id: "arrays", title: "Store a group in an array", minutes: 11, objective: "Create an array and read an item.", language: "JavaScript", explanation: ["An array stores an ordered group inside square brackets.", "Indexes start at 0, so the second item is at 1."], keyTerms: ["array", "item", "index"], exampleTitle: "Three topics", exampleCode: "const topics = [\"Design\", \"Science\", \"Music\"];\nconst first = topics[0];", exampleExplanation: "topics[0] reads the first value.", task: "Create a three-item tools array and store its second item in chosenTool.", starterFiles: files("<p>Use an array.</p>", "", "// Create tools\n// Read the second item"), editableFiles: ["javascript"], tests: [t("javascript", "tools has at least three values", "(?:const|let)\\s+tools\\s*=\\s*\\[[^\\]]+,[^\\]]+,[^\\]]+\\]"), t("javascript", "chosenTool reads index 1", "(?:const|let)\\s+chosenTool\\s*=\\s*tools\\s*\\[\\s*1\\s*\\]")], hints: ["Use square brackets.", "Separate values with commas.", "The second item is tools[1]."], question: q("What is the first array index?", "0", "1", "-1", "JavaScript arrays begin at 0.") },
      { id: "loops", title: "Repeat work with a loop", minutes: 14, objective: "Use forEach with an array.", language: "JavaScript", explanation: ["A loop repeats instructions without copying them.", "forEach runs once for each array item."], keyTerms: ["loop", "forEach", "iteration"], exampleTitle: "Use every topic", exampleCode: "topics.forEach(function (topic) {\n  console.log(topic);\n});", exampleExplanation: "The function runs once for each topic.", task: "Use forEach to add every skill to output.", starterFiles: files("<p id=\"output\"></p>", "", "const skills = [\"HTML\", \"CSS\", \"JavaScript\"];\nlet output = \"\";\n// Add the loop\ndocument.querySelector(\"#output\").textContent = output;"), editableFiles: ["javascript"], tests: [t("javascript", "forEach processes every skill", "skills\\.forEach\\s*\\(\\s*function\\s*\\(\\s*skill\\s*\\)[\\s\\S]*output\\s*(?:\\+=|=\\s*output\\s*\\+)")], hints: ["Begin with skills.forEach.", "Name the current item skill.", "Add skill to output inside the function."], question: q("Why loop over an array?", "To repeat a job for its items", "To create an image", "To rename a browser", "Loops process repeated data efficiently.") },
    ],
    project: { id: "project", title: "Generate content from data", minutes: 25, objective: "Use an array, condition and loop together.", language: "Web project", explanation: ["Replace repeated hand-written output with organised data and code."], keyTerms: ["data", "condition", "loop"], exampleTitle: "Build a list from data", exampleCode: "topics.forEach(function (topic) { list.innerHTML += `<li>${topic}</li>`; });", exampleExplanation: "The loop creates one li for each value.", task: "Create topics, loop through them and add each item to #topic-list. Show a message when topics exist.", starterFiles: files("<header><h1>{{TITLE}}</h1></header><main><p id=\"message\"></p><ul id=\"topic-list\"></ul></main>", shared.cssProject, "const topics = [\"{{ITEM1}}\", \"{{ITEM2}}\", \"{{ITEM3}}\"];\nconst list = document.querySelector(\"#topic-list\");\n// Add the condition and loop"), editableFiles: ["html", "css", "javascript"], tests: [t("javascript", "The project stores three topics", "const\\s+topics\\s*=\\s*\\[[^\\]]+,[^\\]]+,[^\\]]+\\]"), t("javascript", "A condition checks topics", "if\\s*\\([^)]*topics"), t("javascript", "A loop processes topics", "topics\\.forEach\\s*\\("), t("javascript", "The loop adds list item HTML", "innerHTML\\s*(?:\\+=|=)[\\s\\S]*<li>")], hints: ["Check topics.length.", "Run forEach after selecting the list.", "Add one li string per loop."], question: q("Why store content in an array?", "Related values stay together and can be processed", "It replaces all HTML", "It creates a browser", "Arrays organise related data."), reflection: "Which repeated instruction did your loop remove?" },
    projectQuestion: q("What builds several list items from data?", "An array and loop", "A border and margin", "A heading and image", "The array stores values and the loop processes them."),
  }),
  makeStage({
    id: "dom-interaction", number: 7, title: "Make the page interactive", description: "Connect buttons and fields to JavaScript.", outcome: "Controls that respond with clear feedback.",
    challenges: [
      { id: "select", title: "Select an element", minutes: 10, objective: "Find and store an HTML element.", language: "JavaScript", explanation: ["The DOM represents the page as objects JavaScript can use.", "querySelector accepts a CSS selector and returns the matching element."], keyTerms: ["DOM", "querySelector", "element"], exampleTitle: "Store a button", exampleCode: "const openButton = document.querySelector(\"#open-button\");", exampleExplanation: "The variable now refers to that button.", task: "Store #details in a variable named details.", starterFiles: files("<section id=\"details\">Details</section>", "", "// Select the section"), editableFiles: ["javascript"], tests: [t("javascript", "details stores the #details element", "(?:const|let)\\s+details\\s*=\\s*document\\.querySelector\\([\"']#details[\"']\\)")], hints: ["Begin with const details =.", "Call document.querySelector.", "Pass #details inside quotes."], question: q("What does querySelector receive?", "A CSS selector", "A password", "A file download", "querySelector uses a CSS selector.") },
      { id: "events", title: "Respond to a click", minutes: 13, objective: "Run code after a button click.", language: "JavaScript", explanation: ["An event is something that happens in the browser.", "addEventListener connects an event to a function."], keyTerms: ["event", "event listener", "click"], exampleTitle: "A working button", exampleCode: "button.addEventListener(\"click\", function () { message.textContent = \"Button used\"; });", exampleExplanation: "The function waits for the click.", task: "Make the button change #message to Details opened.", starterFiles: files("<button id=\"open-button\">Open</button><p id=\"message\">Waiting</p>", "", "const button = document.querySelector(\"#open-button\");\nconst message = document.querySelector(\"#message\");\n// Add the click listener"), editableFiles: ["javascript"], tests: [t("javascript", "The button listens for click", "button\\.addEventListener\\s*\\(\\s*[\"']click[\"']"), t("javascript", "The click changes the message", "addEventListener[\\s\\S]*message\\.textContent\\s*=\\s*[\"']Details opened[\"']")], hints: ["Call addEventListener on button.", "The event name is click.", "Change message.textContent inside the function."], question: q("When does the listener function run?", "When its event happens", "Before HTML exists", "When CSS has an error", "The listener waits for its event.") },
      { id: "classes", title: "Toggle a class", minutes: 12, objective: "Use classList.toggle to change state.", language: "JavaScript", explanation: ["JavaScript can change classes while CSS controls their appearance.", "toggle adds a class when missing and removes it when present."], keyTerms: ["classList", "toggle", "state"], exampleTitle: "Switch a class", exampleCode: "details.classList.toggle(\"is-open\");", exampleExplanation: "Each call switches is-open on or off.", task: "Toggle is-highlighted on the article after a click.", starterFiles: files("<button id=\"highlight\">Highlight</button><article id=\"article\">Important</article>", ".is-highlighted { background: #f2bf62; }", "const button = document.querySelector(\"#highlight\");\nconst article = document.querySelector(\"#article\");\nbutton.addEventListener(\"click\", function () {\n  // Toggle the class\n});"), editableFiles: ["javascript"], tests: [t("javascript", "The click toggles is-highlighted", "article\\.classList\\.toggle\\s*\\(\\s*[\"']is-highlighted[\"']")], hints: ["Use article inside the click function.", "Call classList.toggle.", "Pass is-highlighted as text."], question: q("What does classList.toggle do?", "Adds or removes one class", "Deletes HTML", "Changes a number to an image", "toggle switches a named class.") },
      { id: "forms", title: "Read visitor input", minutes: 14, objective: "Read a value after form submission.", language: "JavaScript", explanation: ["An input's value property contains what was typed.", "preventDefault keeps the practice page from reloading before code handles the form."], keyTerms: ["value", "submit", "preventDefault"], exampleTitle: "Read a submitted value", exampleCode: "form.addEventListener(\"submit\", function (event) {\n  event.preventDefault();\n  output.textContent = input.value;\n});", exampleExplanation: "The submitted input appears in output.", task: "On submit, prevent reload and show input.value in #result.", starterFiles: files("<form id=\"topic-form\"><label for=\"topic\">Topic</label><input id=\"topic\"><button>Show</button></form><p id=\"result\"></p>", "", "const form = document.querySelector(\"#topic-form\");\nconst input = document.querySelector(\"#topic\");\nconst result = document.querySelector(\"#result\");\n// Handle the form"), editableFiles: ["javascript"], tests: [t("javascript", "The form listens for submit", "form\\.addEventListener\\s*\\(\\s*[\"']submit[\"']"), t("javascript", "Submission is prevented", "event\\.preventDefault\\s*\\("), t("javascript", "The result uses input.value", "result\\.textContent\\s*=\\s*input\\.value")], hints: ["Give the listener an event parameter.", "Call event.preventDefault first.", "Assign input.value to result.textContent."], question: q("Where is typed input text stored?", "Its value property", "Its border", "Its href", "value provides the current input text.") },
    ],
    project: { id: "project", title: "Build a working interaction", minutes: 28, objective: "Connect a form to useful behaviour.", language: "Web project", explanation: ["A visitor should understand the control, use it and receive visible feedback."], keyTerms: ["interaction", "event", "feedback"], exampleTitle: "Interaction flow", exampleCode: "Select form → listen for submit → read value → update page", exampleExplanation: "Each step has one testable job.", task: "When the form is submitted, show the entered topic in #result and add is-ready.", starterFiles: files("<header><h1>{{TITLE}}</h1></header><main><p>{{INTRO}}</p><form id=\"topic-form\"><label for=\"topic\">Choose a topic</label><input id=\"topic\" required><button>Update page</button></form><p id=\"result\">Your choice appears here.</p></main>", shared.cssProject + "\n.is-ready { border-left: 5px solid #5a2676; padding-left: 1rem; }", "const form = document.querySelector(\"#topic-form\");\nconst input = document.querySelector(\"#topic\");\nconst result = document.querySelector(\"#result\");\n// Build the interaction"), editableFiles: ["html", "css", "javascript"], tests: [t("html", "The input has a connected label", "<label[^>]+for=[\"']topic[\"'][^>]*>[\\s\\S]*<input[^>]+id=[\"']topic[\"']"), t("javascript", "The form listens for submit", "form\\.addEventListener\\s*\\(\\s*[\"']submit[\"']"), t("javascript", "The result uses the input value", "result\\.textContent\\s*=[^;]*input\\.value"), t("javascript", "The result receives is-ready", "result\\.classList\\.(?:add|toggle)\\s*\\(\\s*[\"']is-ready[\"']")], hints: ["Connect the submit listener first.", "Prevent the reload before reading input.", "Update textContent, then add the class."], question: q("What should feedback do?", "Show the result of an action clearly", "Hide the control", "Reload every second", "Feedback confirms what happened."), reflection: "What can a visitor do on your page now?" },
    projectQuestion: q("Which event handles a completed form?", "submit", "colour", "margin", "Forms produce a submit event."),
  }),
  makeStage({
    id: "quality", number: 8, title: "Test and finish the website", description: "Repair errors, improve access and prepare a safe final version.", outcome: "A tested website the learner can demonstrate and explain.",
    challenges: [
      { id: "html", title: "Repair broken HTML", minutes: 11, objective: "Fix mismatched closing tags.", language: "HTML", explanation: ["Debugging starts by comparing expected and actual results.", "Check opening tags, closing tags and nesting before changing unrelated code."], keyTerms: ["debugging", "expected result", "actual result"], exampleTitle: "Matched tags", exampleCode: "<section><h2>News</h2></section>", exampleExplanation: "The h2 closes before the section.", task: "Repair the heading and paragraph tags.", starterFiles: files("<section>\n  <h2>Latest article</h3>\n  <p>Read the new story.</div>\n</section>"), editableFiles: ["html"], tests: [t("html", "The h2 closes correctly", "<h2>Latest article</h2>"), t("html", "The paragraph closes correctly", "<p>Read the new story\\.</p>")], hints: ["Compare each opening and closing tag.", "The heading begins with h2.", "The paragraph begins with p."], question: q("What should you compare first?", "Expected and actual behaviour", "Two random colours", "Age and nickname", "The difference guides the repair.") },
      { id: "syntax", title: "Repair CSS and JavaScript", minutes: 13, objective: "Fix one error in each language.", language: "JavaScript", explanation: ["Small punctuation and spelling mistakes can stop code.", "Read the exact line, change one thing and run again."], keyTerms: ["syntax", "error", "test"], exampleTitle: "Two repairs", exampleCode: ".card { color: #111936; }\nconst card = document.querySelector(\".card\");", exampleExplanation: "CSS uses a colon and querySelector is spelled correctly.", task: "Repair the CSS declaration and querySelector spelling.", starterFiles: files("<article class=\"card\">Test</article>", ".card { color = #111936; }", "const card = document.querySelecter(\".card\");\ncard.textContent = \"Repair complete\";"), editableFiles: ["css", "javascript"], tests: [t("css", "CSS uses a colon", "color\\s*:\\s*#111936"), t("javascript", "querySelector is correct", "document\\.querySelector\\(")], hints: ["CSS uses a colon between property and value.", "Compare the method name with earlier lessons.", "Repair only the two broken pieces."], question: q("Why change one thing before running?", "It identifies which change solved the problem", "It makes the file longer", "It hides the error", "Small changes give useful evidence.") },
      { id: "access", title: "Check accessibility", minutes: 13, objective: "Use alt text, labels and keyboard focus.", language: "CSS", explanation: ["Accessible code helps more people use a webpage.", "Images need descriptions, inputs need labels and controls need visible focus."], keyTerms: ["accessibility", "keyboard focus", "focus-visible"], exampleTitle: "Visible keyboard focus", exampleCode: "button:focus-visible { outline: 3px solid #ee9d2b; }", exampleExplanation: "The outline shows the currently selected control.", task: "Add alt text, connect the label and style button focus.", starterFiles: files("<img src=\"photo.jpg\">\n<label>Search</label><input id=\"search\">\n<button>Search</button>", "/* Add focus style */"), editableFiles: ["html", "css"], tests: [t("html", "The image has alt text", "<img[^>]+alt=[\"'][^\"']{5,}[\"']"), t("html", "The label connects to search", "<label[^>]+for=[\"']search[\"']"), t("css", "Button focus is visible", "button:focus-visible\\s*\\{[\\s\\S]*outline\\s*:")], hints: ["Describe the image with alt.", "Add for=search to the label.", "Use button:focus-visible with outline."], question: q("Why show keyboard focus?", "It shows which control is selected", "It reloads the page", "It replaces labels", "A focus indicator helps keyboard users follow position.") },
      { id: "sharing", title: "Write a safe project note", minutes: 10, objective: "Describe the work without personal details.", language: "HTML", explanation: ["A project note should state what was built and which technologies were used.", "Use a nickname. Do not publish a full name, school, phone number, home address or exact location."], keyTerms: ["project note", "privacy", "credit"], exampleTitle: "A safe creator note", exampleCode: "<footer><p>Built by SkyCoder using HTML, CSS and JavaScript.</p></footer>", exampleExplanation: "It credits the skill without identifying the child.", task: "Write a footer note with a nickname and all three technologies.", starterFiles: files("<footer>\n  <!-- Add the safe note -->\n</footer>"), editableFiles: ["html"], tests: [t("html", "The note mentions HTML", "HTML"), t("html", "The note mentions CSS", "CSS"), t("html", "The note mentions JavaScript", "JavaScript"), t("html", "The note is in a footer", "<footer[\\s>][\\s\\S]+</footer>")], hints: ["Begin with Built by and a nickname.", "Name HTML, CSS and JavaScript.", "Keep the sentence inside footer."], question: q("What stays off a public child project?", "School and exact location", "Technologies used", "Project title", "Identifying location details should stay private.") },
    ],
    project: { id: "project", title: "Complete the final website", minutes: 35, objective: "Finish, test and explain a responsive interactive website.", language: "Web project", explanation: ["A finished project meets its requirements, has been tested and can be explained.", "Keep every feature purposeful and repair only what the checks show is missing."], keyTerms: ["final build", "testing", "explanation"], exampleTitle: "Final evidence", exampleCode: "Structure works\nDesign responds\nInteraction gives feedback\nCreator explains one repair", exampleExplanation: "The evidence checks knowledge and skill.", task: "Finish with semantic HTML, responsive CSS, one interaction and a safe creator note.", starterFiles: files(shared.htmlProject.replace("Built while learning web development.", "Built by SkyCoder using HTML, CSS and JavaScript."), shared.cssProject + "\nbutton:focus-visible { outline: 3px solid #ee9d2b; outline-offset: 3px; }", "const button = document.querySelector(\"button\");\nbutton.addEventListener(\"click\", function () {\n  document.querySelector(\"h1\").textContent = \"Thanks for visiting\";\n});"), editableFiles: ["html", "css", "javascript"], tests: [t("html", "The page uses semantic regions", "<header[\\s>][\\s\\S]*<main[\\s>][\\s\\S]*<footer[\\s>]"), t("css", "The layout has a media query", "@media\\s*\\("), t("javascript", "The page has an event listener", "addEventListener\\s*\\("), t("javascript", "The interaction updates content", "textContent\\s*="), t("html", "The footer names all three technologies", "<footer[\\s\\S]*HTML[\\s\\S]*CSS[\\s\\S]*JavaScript[\\s\\S]*</footer>")], hints: ["Run the current version first.", "Check structure, design and interaction separately.", "Repair only the missing requirement."], question: q("What proves practical coding skill?", "A working website the learner can explain", "The number of pages opened", "A badge alone", "A working, tested and explained product proves skill."), reflection: "What can you build now that you could not build before?" },
    projectQuestion: q("What is the strongest final evidence?", "Working code, passed checks and an explanation", "A long activity total", "A colourful screen without working controls", "The product, tests and explanation show understanding."),
  }),
];

export const lessons = stages.flatMap((stage) => stage.lessons);

export const finalExam: PracticeQuestion[] = [
  q("Which element is the main page heading?", "h1", "p", "a", "h1 represents the main heading."),
  q("Which attribute describes an image?", "alt", "href", "className", "alt provides an alternative description."),
  q("How does CSS select class card?", ".card", "#card", "<card>", "A class selector begins with a full stop."),
  q("What creates space inside a border?", "padding", "margin", "display", "Padding creates inner space."),
  q("What is useful for a row of links?", "Flexbox", "alt text", "querySelector", "Flexbox controls one-dimensional layouts."),
  q("What declares a changing JavaScript variable?", "let", "href", "style", "let creates a reassignable variable."),
  q("What does a condition produce?", "A true or false decision", "An image", "A border", "A condition evaluates to true or false."),
  q("What is the first array index?", "0", "1", "10", "Array indexing begins at 0."),
  q("What connects a click to JavaScript?", "An event listener", "An h1", "A media query", "An event listener runs code after a click."),
  q("What should happen first when code fails?", "Compare expected and actual behaviour", "Rewrite every file", "Add random code", "A clear comparison guides repair."),
];

export const practicalExam = {
  title: "Repair a small webpage",
  language: "HTML and JavaScript",
  brief: "Repair the heading tag, correct querySelector and make the button change the message to Ready.",
  starterCode: "<h2>Final check</h3>\n<button id=\"check\">Check work</button>\n<p id=\"message\">Waiting</p>\n\n<script>\nconst button = document.querySelecter(\"#check\");\nconst message = document.querySelector(\"#message\");\nbutton.addEventListener(\"click\", function () {\n  message.textContent = \"\";\n});\n</script>",
  requiredPatterns: [
    "</h2>",
    "querySelector\\(\\s*[\"']#check[\"']\\s*\\)",
    "textContent\\s*=\\s*[\"']Ready[\"']",
  ],
};

export const courseFacts = { title: "Web Coding Foundations", ageRange: "Ages 10 to 12", lessonCount: lessons.length, stageCount: stages.length, estimatedHours: "18 to 22 hours", passMark: 7 };
