import type { ConceptRule } from "@/lib/tutor";

/*
 * These rules cover the requirement wording used by the ages 13 to 18 and adult
 * pathways, where labels describe JavaScript behaviour, layout decisions and
 * written reflection. They run after the language rules in lib/tutor.ts so the
 * more specific wording still wins. A recognisable label always produces a
 * concept, a focus area and graduated support rather than a generic reply.
 */
export const pathwayConceptRules: ConceptRule[] = [
  {
    key: "section-heading",
    focus: "Section heading",
    match: /about this page heading/i,
    hint: "The section needs its own heading one level below the page title. Look for the heading element that introduces it.",
    explanation: "An h2 element introduces a section inside the page. It sits below h1 in importance and is written with its own opening and closing tag.",
    example: "<h2>About this page</h2>",
    acknowledgement: "You introduced the section with its own heading, so the page now has a clear structure to follow.",
  },
  {
    key: "link-destination",
    focus: "Link destination",
    match: /working link|link to|links to/i,
    hint: "The link element is in place, but the browser does not yet know where it should go. Name the attribute that stores an address on a link.",
    explanation: "An a element stores its destination in the href attribute. Writing the full address inside href is what makes the words clickable.",
    example: '<a href="https://example.com">Read more</a>',
    acknowledgement: "You set the link destination with href, so the words now lead somewhere real.",
  },
  {
    key: "class-toggling",
    focus: "Switching a class",
    match: /receives is-ready|classlist|switches class|toggles class/i,
    hint: "The element already exists. Look for the step that adds or removes a class name on it, because that is what changes its appearance.",
    explanation: "classList.add and classList.remove change which class names an element carries, so a style rule already in the stylesheet starts or stops applying.",
    example: 'result.classList.add("is-ready");',
    acknowledgement: "You changed the class name on the element, which is what switches its appearance without rewriting the HTML.",
  },
  {
    key: "visible-focus",
    focus: "Visible keyboard focus",
    match: /focus-visible|keyboard focus|focus is visible|uses an outline|offsets the outline/i,
    hint: "A keyboard visitor needs to see where they are. Check that the focus style has not been removed and that the marker stays visible.",
    explanation: ":focus-visible styles the control a keyboard visitor has reached. An outline draws that marker, and outline-offset keeps it clear of the border.",
    example: "button:focus-visible {\n  outline: 3px solid #ee9d2b;\n  outline-offset: 3px;\n}",
    acknowledgement: "You kept a visible focus style, which is what lets a keyboard visitor follow the page.",
  },
  {
    key: "custom-properties",
    focus: "Reusable CSS values",
    match: /custom propert|defines three properties|uses (text|accent|space) property/i,
    hint: "The same value is repeated in more than one place. Look for the way CSS stores a value once and reuses it by name.",
    explanation: "A custom property is declared on :root with two leading dashes and reused through var(). Changing it once updates every rule that uses it.",
    example: ":root {\n  --accent: #ee9d2b;\n}\nh1 { color: var(--accent); }",
    acknowledgement: "You stored the value once and reused it by name, which is how a stylesheet stays consistent.",
  },
  {
    key: "async-data",
    focus: "Fetching and showing data",
    match: /await|fetch|async |response status|reads json|shows loading|stale|request id/i,
    hint: "The code uses the data before it has arrived. Look for the keyword that waits for a task to finish before its result is used.",
    explanation: "An async function can pause on await. The await keyword waits for the request to finish and gives back the response, so the data exists only after that line.",
    example: 'async function loadData() {\n  const response = await fetch("/api/items");\n}',
    acknowledgement: "You waited for the request before using its result, which is what stops the page reading empty data.",
  },
  {
    key: "input-cleaning",
    focus: "Cleaning the input",
    match: /trims the value|validates|checks empty/i,
    hint: "The value comes from a visitor, so it may arrive with extra spaces or nothing at all. Check that the value is checked before it is used.",
    explanation: "Trimming removes spacing from the ends of a value, and a check before use stops empty input from reaching the rest of the code.",
    example: "const title = input.value.trim();\nif (title.length > 0) {\n  addRecord(title);\n}",
    acknowledgement: "You checked the visitor's input before using it, which is what keeps empty or messy values out of the data.",
  },
  {
    key: "error-handling",
    focus: "Handling problems safely",
    match: /\btry\b|\bcatch\b|finally|fallback|removes innerhtml/i,
    hint: "Something here can fail, so the code needs a path for when it does. Look for the block that handles a failure instead of stopping the page.",
    explanation: "Code inside try runs normally, catch receives a problem instead of letting it stop the page, and finally always runs. That is how a page stays usable when something goes wrong.",
    example: 'try {\n  render(items);\n} catch (error) {\n  status.textContent = "Please try again";\n}',
    acknowledgement: "You gave the failure its own path, so the page reports a problem instead of breaking.",
  },
  {
    key: "array-methods",
    focus: "Working through a list of items",
    match: /foreach|uses map|calls map|\bmap\b|uses filter|calls filter|\bfilter\b|calls sort|\bsort\b|new array|loops through|loop creates|a loop |creates three topics|current item|current skill|adds each/i,
    hint: "The code needs to visit each item in the list. Look for the method that runs once for every item instead of writing the same line many times.",
    explanation: "A loop or an array method such as forEach, map or filter runs the same instructions once for every item, and the current item is available inside that run.",
    example: "skills.forEach(function (skill) {\n  addItem(skill);\n});",
    acknowledgement: "You worked through the list item by item, which is what keeps the code short and repeatable.",
  },
  {
    key: "create-append",
    focus: "Adding elements to the page",
    match: /creates an element|creates li|appends|appended|safe text/i,
    hint: "The code builds something new, then it needs to place that element on the page. Look for the moment the new element joins its parent.",
    explanation: "createElement builds an element in memory. It appears on the page only after append places it inside an existing parent, and safe text keeps visitor input from becoming markup.",
    example: 'const item = document.createElement("li");\nitem.textContent = skill;\nlist.append(item);',
    acknowledgement: "You built the element and placed it inside its parent, which is how a page grows without reloading.",
  },
  {
    key: "page-areas",
    focus: "Page areas",
    match: /\barea\b|\bregion\b/i,
    hint: "The page needs a place where this text can appear. Check that the element exists in the HTML with the id the task names.",
    explanation: "JavaScript can only update an element that already exists on the page, so the HTML needs that element with a matching id before the script runs.",
    example: '<p id="summary">Summary loading...</p>',
    acknowledgement: "You created the element the script needs, which is what gives the output somewhere to appear.",
  },
  {
    key: "element-selection",
    focus: "Finding the element",
    match: /queryselector|stores the matching element|find #|selects|finds an html element/i,
    hint: "JavaScript needs to find the element before it can change it. Check the selector and whether it matches the element in the HTML.",
    explanation: "document.querySelector finds the first element that matches a CSS selector. An id selector is written with a hash, so #status finds the element with id=\"status\".",
    example: 'const status = document.querySelector("#status");',
    acknowledgement: "You selected the element with a matching selector, which is the step that lets later code reach the right part of the page.",
  },
  {
    key: "changing-text",
    focus: "Changing visible text",
    match: /updates visible text|displays the result|saves a value|saves the topic|becomes visible text|updates visitcount|updates the welcome|shows feedback|feedback/i,
    hint: "The element is found. The browser still needs to be told to replace what it shows. Look for the property that holds an element's visible text.",
    explanation: "After an element is selected, its textContent property can be assigned new words. Assigning with the equals sign replaces exactly what the visitor reads.",
    example: 'result.textContent = "Ready";',
    acknowledgement: "You replaced the visible text, which changes what the visitor reads without changing the page structure.",
  },
  {
    key: "event-handling",
    focus: "Responding to events",
    match: /event|click|addeventlistener|listener|listens for|interaction/i,
    hint: "The code needs to wait for something the visitor does. Look for the method that listens for an event, then check the event name inside it.",
    explanation: "addEventListener attaches a function to an event name, so the function runs when that event happens, such as \"click\" or \"submit\".",
    example: 'form.addEventListener("submit", loadData);',
    acknowledgement: "You listened for the event and attached the right function, which is what makes the page respond to the visitor.",
  },
  {
    key: "form-controls",
    focus: "Form controls",
    match: /fieldset|legend|radios share|\bform\b|submit|help text|button/i,
    hint: "The control group is almost complete. Check that each control carries the name or label it needs so a visitor knows what to enter.",
    explanation: "A fieldset groups related controls and its legend describes the group. Radio buttons share one name so only one can be chosen, and each control carries a label.",
    example: '<fieldset>\n  <legend>Age</legend>\n  <input id="age" name="age" type="radio">\n</fieldset>',
    acknowledgement: "You grouped and named the controls, which is what makes the form understandable.",
  },
  {
    key: "record-object",
    focus: "Objects and their properties",
    match: /object|record|propert|\bcategory\b|title|compar|excludes the id|spread/i,
    hint: "The stored value has several named parts. Check that each part is read and written with exactly the name it was given.",
    explanation: "An object groups named properties, and each property is read with its own name. Copying with spread syntax keeps the existing properties while changing one of them.",
    example: 'const item = { title: "Loops", category: "basics" };\nitem.title',
    acknowledgement: "You grouped the values under names and read them back by name, which is what makes the record reliable.",
  },
  {
    key: "function-definition",
    focus: "Defining and calling a function",
    match: /defines|calls|returns|\bis defined\b|function/i,
    hint: "A function is defined in one place and used in another. Check the definition first, then find the line that uses it.",
    explanation: "Defining a function prepares a named job. It runs only when it is called, and the return statement hands a value back to the line that called it.",
    example: "function calculateTotal(items) {\n  return items.length;\n}\ncalculateTotal(list);",
    acknowledgement: "You defined the job and returned a value, so the rest of the code can reuse it.",
  },
  {
    key: "index-length",
    focus: "Reading a value from a list",
    match: /index|length|checks available/i,
    hint: "The code needs a specific value from the list. Check whether the position starts at zero, and whether that position exists at all.",
    explanation: "Array positions are counted from zero, so the first item sits at index 0. The length property reports how many items exist, which is how the code checks before reading.",
    example: "const first = items[0];\nconst total = items.length;",
    acknowledgement: "You read the list by position and checked its size, which is what avoids reading an item that is not there.",
  },
  {
    key: "decisions",
    focus: "Making a decision",
    match: /outcome|is ready|true result|boundary|checks for more than|condition|\bif \b|else/i,
    hint: "The code needs a question with a true or false answer. Check the comparison inside the brackets.",
    explanation: "An if statement runs its block only when the condition is true. A comparison such as ===, > or >= produces that true or false answer.",
    example: 'if (count >= 4) {\n  status.textContent = "Ready";\n}',
    acknowledgement: "You wrote a comparison the code can decide on, which is what makes the branch predictable.",
  },
  {
    key: "state-storage",
    focus: "Remembering state",
    match: /state|localstorage|storage|store|saves|remember/i,
    hint: "The page needs to remember something between actions. Check where the value is kept and whether it is read back before it is used.",
    explanation: "State is the information the page keeps while the visitor works. Reading it back before updating is what stops an action from wiping earlier work.",
    example: 'const saved = localStorage.getItem("items");',
    acknowledgement: "You kept the value and read it back, which is what lets the page remember state between actions.",
  },
  {
    key: "semantic-region",
    focus: "Meaningful page regions",
    match: /header|main region|\bfooter\b|semantic|three div|uses main|uses navigation|has navigation|uses a section/i,
    hint: "The page has the right content. The region names still need to say what each part does. Check the tag that introduces the page, holds its central content and closes it.",
    explanation: "Semantic elements name the job of a region: header introduces the page, nav groups its links, main holds the central content and footer closes it.",
    example: "<header><h1>Guide</h1></header>\n<main><p>Main information.</p></main>\n<footer><p>Practice project.</p></footer>",
    acknowledgement: "You used semantic region names, so each part of the page now states its own job.",
  },
  {
    key: "documentation",
    focus: "Explaining your work",
    match: /mentions|names a limitation|names tested|records .* evidence|names the three|version heading|release notes/i,
    hint: "This requirement is about the written explanation rather than the code. Check that each claim names the evidence it rests on.",
    explanation: "A useful explanation states what was tested, what the result was and where the limits are, so a reader can trust the claim without guessing.",
    example: "Tested: the form submits and shows the total.\nLimit: it does not save between visits.",
    acknowledgement: "You stated the evidence behind the claim, which is what makes the explanation trustworthy.",
  },
  {
    key: "flex-alignment",
    focus: "Arranging a flexible row",
    match: /wraps|aligns items|is flexible/i,
    hint: "The row runs out of space or sits unevenly on some screens. Check how the container should behave when its items do not fit.",
    explanation: "flex-wrap lets a row move items onto the next line instead of squeezing them, and align-items lines the items up against each other.",
    example: "nav { display: flex; flex-wrap: wrap; align-items: center; }",
    acknowledgement: "You decided how the row behaves when space is tight, which keeps the layout steady.",
  },
  {
    key: "layout-tracks",
    focus: "Columns and breakpoints",
    match: /repeat|flexible tracks|one column|tracks|responsive rules|700px|breakpoint/i,
    hint: "The layout needs a clear column plan for a narrow and a wide screen. Check the rule that describes the columns in each case.",
    explanation: "grid-template-columns describes the columns, repeat keeps them equal, and a media query changes the column count when the screen width changes.",
    example: ".grid { display: grid; grid-template-columns: repeat(2, 1fr); }\n@media (max-width: 700px) { .grid { grid-template-columns: 1fr; } }",
    acknowledgement: "You described the columns for both screen sizes, which is what makes the layout adapt on purpose.",
  },
  {
    key: "sizing-overflow",
    focus: "Keeping content inside its space",
    match: /fluid width|has a maximum|overflow|viewport metadata/i,
    hint: "Content can grow wider than its container. Look for the limit that keeps it inside the space it was given.",
    explanation: "max-width limits how wide an element can grow, and an image with max-width: 100% cannot overflow its parent on a narrow screen.",
    example: "img { max-width: 100%; height: auto; }",
    acknowledgement: "You set a limit, which is what stops content from spilling out of its container.",
  },
  {
    key: "stylesheet-structure",
    focus: "Stylesheet structure",
    match: /styles the body|styles cards|links have their own rule|uses a colon|is a colon/i,
    hint: "The rule needs to name the element it styles. Check the selector before the braces, then each declaration inside them.",
    explanation: "A CSS rule starts with a selector, then declarations inside braces. Each declaration is a property, a colon, a value and a semicolon.",
    example: "body { background: #f7f3ea; }",
    acknowledgement: "You wrote a complete rule for the right element, which is the shape every stylesheet follows.",
  },
  {
    key: "element-id",
    focus: "Element id",
    match: /\bid\b|has an id/i,
    hint: "An element needs a name that other code can find. Look for the attribute that gives one element its own identity.",
    explanation: "The id attribute names a single element. It must be unique on the page, and code finds it with a selector such as #summary.",
    example: '<p id="summary">Summary loading...</p>',
    acknowledgement: "You gave the element its own id, which is how the rest of the page can find it reliably.",
  },
];
